#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WEB="$(cd "$ROOT/../web" && pwd)"
REPO="$(cd "$ROOT/.." && pwd)"
cd "$ROOT"

if [ ! -f "$ROOT/.env" ]; then
  echo "Missing contracts/.env with PRIVATE_KEY=0x..."
  exit 1
fi
# shellcheck disable=SC1091
set -a
source "$ROOT/.env"
set +a

: "${PRIVATE_KEY:?PRIVATE_KEY required}"
PAY_TO="${PAY_TO:-}"
HOUSE_FUND_WEI="${HOUSE_FUND_WEI:-200000000000000000}"

ADDR="$(cast wallet address --private-key "$PRIVATE_KEY")"
BAL="$(cast balance "$ADDR" --rpc-url https://testnet-rpc.monad.xyz)"
echo "Deployer $ADDR  balance $BAL wei"
if [ "$BAL" = "0" ]; then
  echo "Fund this address on https://faucet.monad.xyz then re-run."
  exit 1
fi

if [ -z "$PAY_TO" ]; then
  PAY_TO="$ADDR"
fi

LISTING_FEE_WEI="${LISTING_FEE_WEI:-50000000000000000}"
TREASURY="${TREASURY:-$ADDR}"
# Set REUSE_DEVIL_ESCROW to an existing escrow address to keep its house balance.
REUSE_DEVIL_ESCROW="${REUSE_DEVIL_ESCROW:-0x0000000000000000000000000000000000000000}"
if [ "$REUSE_DEVIL_ESCROW" = "none" ]; then
  REUSE_DEVIL_ESCROW="0x0000000000000000000000000000000000000000"
  SKIP_ESCROW_GUARD=1
fi

echo "Listing fee   $LISTING_FEE_WEI wei"
echo "Treasury      $TREASURY"
if [ "$REUSE_DEVIL_ESCROW" != "0x0000000000000000000000000000000000000000" ]; then
  echo "Reusing escrow $REUSE_DEVIL_ESCROW (not redeploying, house balance kept)"
elif [ -z "$SKIP_ESCROW_GUARD" ]; then
  # DevilEscrow has no withdraw path, so a fresh deploy permanently strands whatever
  # the previous escrow still holds. Refuse to do that silently.
  PREV="$(grep -m1 '^NEXT_PUBLIC_DEVIL_ESCROW=' "$ROOT/../web/.env" 2>/dev/null | cut -d= -f2 | tr -d ' \r')"
  if [ -n "$PREV" ]; then
    PREV_BAL="$(cast balance "$PREV" --rpc-url https://testnet-rpc.monad.xyz 2>/dev/null || echo 0)"
    if [ "${PREV_BAL:-0}" != "0" ]; then
      echo "REFUSING: escrow $PREV still holds $PREV_BAL wei and DevilEscrow cannot withdraw."
      echo "Set REUSE_DEVIL_ESCROW=$PREV to keep it, or REUSE_DEVIL_ESCROW=none to strand it on purpose."
      exit 1
    fi
  fi
fi

PAY_TO="$PAY_TO" HOUSE_FUND_WEI="$HOUSE_FUND_WEI" PRIVATE_KEY="$PRIVATE_KEY" \
LISTING_FEE_WEI="$LISTING_FEE_WEI" TREASURY="$TREASURY" REUSE_DEVIL_ESCROW="$REUSE_DEVIL_ESCROW" \
  forge script script/Deploy.s.sol:Deploy \
    --rpc-url https://testnet-rpc.monad.xyz \
    --broadcast \
    --legacy

LATEST="$ROOT/broadcast/Deploy.s.sol/10143/run-latest.json"
if [ ! -f "$LATEST" ]; then
  echo "broadcast file missing"
  exit 1
fi

# create + 3 contracts in order: Registry, Router, Escrow (escrow is last created)
REGISTRY="$(jq -r '.transactions[] | select(.contractName=="AgentRegistry" and .transactionType=="CREATE") | .contractAddress' "$LATEST" | head -1)"
ROUTER="$(jq -r '.transactions[] | select(.contractName=="PaymentRouter" and .transactionType=="CREATE") | .contractAddress' "$LATEST" | head -1)"
ESCROW="$(jq -r '.transactions[] | select(.contractName=="DevilEscrow" and .transactionType=="CREATE") | .contractAddress' "$LATEST" | head -1)"
# No CREATE means we reused an existing escrow.
if [ -z "$ESCROW" ] || [ "$ESCROW" = "null" ]; then
  ESCROW="$REUSE_DEVIL_ESCROW"
fi

echo "REGISTRY=$REGISTRY"
echo "PAYMENT_ROUTER=$ROUTER"
echo "DEVIL_ESCROW=$ESCROW"
echo "PAY_TO=$PAY_TO"

# Deploy outputs only. Secrets and feature flags live in web/.env, and .env.local
# takes precedence over it — writing anything else here would silently override
# a working value with a blank one.
cat > "$WEB/.env.local" <<EOF
# Generated by contracts/script/deploy.sh — deploy outputs only, do not add secrets.
NEXT_PUBLIC_CHAIN_ID=10143
NEXT_PUBLIC_RPC_URL=https://testnet-rpc.monad.xyz
NEXT_PUBLIC_EXPLORER=https://testnet.monadvision.com
NEXT_PUBLIC_REGISTRY=$REGISTRY
NEXT_PUBLIC_PAYMENT_ROUTER=$ROUTER
NEXT_PUBLIC_DEVIL_ESCROW=$ESCROW
NEXT_PUBLIC_PAY_TO=$PAY_TO
EOF

python3 - <<PY
from pathlib import Path
p = Path("$REPO/README.md")
t = p.read_text()
repls = {
    "NEXT_PUBLIC_REGISTRY": "$REGISTRY",
    "NEXT_PUBLIC_PAYMENT_ROUTER": "$ROUTER",
    "NEXT_PUBLIC_DEVIL_ESCROW": "$ESCROW",
}
# keep table usable: write a contracts block
marker = "## Deployed addresses (testnet)"
block = f"""## Deployed addresses (testnet)

- AgentRegistry: [\`{repls['NEXT_PUBLIC_REGISTRY']}\`](https://testnet.monadvision.com/address/{repls['NEXT_PUBLIC_REGISTRY']})
- PaymentRouter: [\`{repls['NEXT_PUBLIC_PAYMENT_ROUTER']}\`](https://testnet.monadvision.com/address/{repls['NEXT_PUBLIC_PAYMENT_ROUTER']})
- DevilEscrow: [\`{repls['NEXT_PUBLIC_DEVIL_ESCROW']}\`](https://testnet.monadvision.com/address/{repls['NEXT_PUBLIC_DEVIL_ESCROW']})
- Pay-to / sink: \`{ "$PAY_TO" }\`
"""
if marker in t:
    pre, rest = t.split(marker, 1)
    # drop old block until next ##
    nxt = rest.find("\n## ", 1)
    t = pre + block + (rest[nxt:] if nxt != -1 else "")
else:
    t = t.replace("## Contracts", block + "\n## Contracts")
p.write_text(t)
print("README updated")
PY

echo "Wrote web/.env.local"
echo "Next: ./script/verify.sh"
